<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:07:39.
 */
class files_permissionModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var files_permissionModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new files_permissionModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers files_permissionModel::getUsersByFolder
     * @todo   Implement testGetUsersByFolder().
     */
    public function testGetUsersByFolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_permissionModel::getUsePermission
     * @todo   Implement testGetUsePermission().
     */
    public function testGetUsePermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
