<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:07:30.
 */
class files_pastaModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var files_pastaModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new files_pastaModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers files_pastaModel::getCodFolder
     * @todo   Implement testGetCodFolder().
     */
    public function testGetCodFolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_pastaModel::userCanAccess
     * @todo   Implement testUserCanAccess().
     */
    public function testUserCanAccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_pastaModel::garbageColector
     * @todo   Implement testGarbageColector().
     */
    public function testGarbageColector() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_pastaModel::getSizeOfFolder
     * @todo   Implement testGetSizeOfFolder().
     */
    public function testGetSizeOfFolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_pastaModel::unstall
     * @todo   Implement testUnstall().
     */
    public function testUnstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_pastaModel::selecionar
     * @todo   Implement testSelecionar().
     */
    public function testSelecionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
