<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:07:34.
 */
class files_arquivoModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var files_arquivoModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new files_arquivoModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers files_arquivoModel::inserir
     * @todo   Implement testInserir().
     */
    public function testInserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::getFileByFolderAndName
     * @todo   Implement testGetFileByFolderAndName().
     */
    public function testGetFileByFolderAndName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::getAllFilesFromFolder
     * @todo   Implement testGetAllFilesFromFolder().
     */
    public function testGetAllFilesFromFolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::getFilesByFolder
     * @todo   Implement testGetFilesByFolder().
     */
    public function testGetFilesByFolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::getFilesByUser
     * @todo   Implement testGetFilesByUser().
     */
    public function testGetFilesByUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::getFile
     * @todo   Implement testGetFile().
     */
    public function testGetFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::getFileByName
     * @todo   Implement testGetFileByName().
     */
    public function testGetFileByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::convertSizeUnity
     * @todo   Implement testConvertSizeUnity().
     */
    public function testConvertSizeUnity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers files_arquivoModel::changeShowFile
     * @todo   Implement testChangeShowFile().
     */
    public function testChangeShowFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
